# Generated by Django 4.2.1 on 2023-06-21 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('collage_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=40)),
                ('student_id', models.IntegerField()),
                ('student_rol', models.IntegerField()),
                ('student_address', models.CharField(max_length=100)),
                ('Collage_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.collage')),
            ],
        ),
    ]
