# Generated by Django 4.2.1 on 2023-06-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Collage_name',
            new_name='collage_name',
        ),
    ]
